from plone import api


SEND_ANYWAY_ENV_VAR = 'GETSENTRY_ALWAYS_SEND'
DSN_ENV_VAR = 'GETSENTRY_DSN'
ENVIRONMENT_ENV_VAR = 'GETSENTRY_ENVIRONMENT'
RELEASE_ENV_VAR = 'GETSENTRY_RELEASE'
TRACK_JS_ENV_VAR = 'GETSENTRY_TRACK_JS'
USER_FEEDBACK_ENV_VAR = 'GETSENTRY_USER_FEEDBACK'
IGNORED_JS = 'GETSENTRY_JS_TO_IGNORE'
IGNORED_JS_ERRORS = 'GETSENTRY_JS_ERRORS_TO_IGNORE'
ALLOWED_JS = 'GETSENTRY_JS_TO_ALLOW'
CA_CERTS_ENV_VAR = 'GETSENTRY_CA_CERTS'
PROXY_ENV_VAR = 'GETSENTRY_PROXY'


IS_PLONE_4 = api.env.plone_version().startswith("4")
IS_PLONE_5 = api.env.plone_version().startswith("5")
